IF
Global("EECorwinScar","Global",2)
InParty("Corwin")
Global("EEMetRohma","Global",0)
THEN
RESPONSE #100
SetGlobal("EEMetRohma","Global",1)
CreateCreature("bdrohma",[245.375],11)
CreateCreature("bdaudam",[154.341],13)
END

IF
GlobalGT("Chapter","Global",7)
InActiveArea("bdrohma")
THEN
RESPONSE #100
ActionOverride("bdrohma",DestroySelf())
END

IF
GlobalGT("Chapter","Global",7)
InActiveArea("bdaudam")
THEN
RESPONSE #100
ActionOverride("bdaudam",DestroySelf())
END