IF
Global("EECorwinScar","Global",2)
InParty("Corwin")
Global("EEMetRohma","Global",0)
THEN
RESPONSE #100
SetGlobal("EEMetRohma","Global",1)
CreateCreature("bdrohma",[285.319],9)
CreateCreature("bdaudam",[454.306],7)
END

IF
GlobalGT("Chapter","Global",%tutu_chapter_7%)
InActiveArea("bdrohma")
THEN
RESPONSE #100
ActionOverride("bdrohma",DestroySelf())
END

IF
GlobalGT("Chapter","Global",%tutu_chapter_7%)
InActiveArea("bdaudam")
THEN
RESPONSE #100
ActionOverride("bdaudam",DestroySelf())
END